### PR TITLE
refact(xsrf) use frau-superagent-xsrf-token. closes #15

### LINKED ISSUE #15: Fetch xsrf token in a more robust manner
A tip from @dlockhart:

See http://stackoverflow.com/questions/14555347/html5-localstorage-error-with-safari-quota-exceeded-err-dom-exception-22-an

We could use `D2L.LP.Web.Authentication.Xsrf.GetXsrfToken()` (maybe only if it exists?) for now. It's not great coupling this library to that code.

### PR DESCRIPTION
**Pull request by omsmith**
I removed tests specific to xsrf tokens. Could be good to still have them, but the logic of what that means is contained within the dep.

R= @dlockhart, @j3parker

### CODE REVIEW

**Comment by dlockhart** [comment]
Looks good

**Comment by omsmith** [comment]
I don't have any buttons

**Comment by dlockhart** [comment]
Haha me neither... @j3parker can you merge?

**Comment by j3parker** [comment]
Haha sorry.

**Pull request merged**
