### PR TITLE
Update superagent

### PR DESCRIPTION
**Pull request by ktonon**
Starting a new project and want to use this with the latest superagent. Not sure what kind of version bump you'd want to do, so I left that out.

### CODE REVIEW

**Comment by omsmith** [comment]
Can you do bumps in the dependencies as well?

https://github.com/Brightspace/frau-jwt/blob/master/package.json
https://github.com/Brightspace/frau-superagent-xsrf-token/blob/master/package.json (dev)
https://github.com/Brightspace/frau-xsrf-token/blob/master/package.json

**Comment by ktonon** [comment]
Ok, working on that now

**Comment by ktonon** [comment]
I don't see `frau-xsrf-token` as a direct dependency

**Comment by omsmith** [comment]
It's used by `frau-superagent-xsrf-token`. I meant bump `superagent`, otherwise you'll definitely have a mix of versions.

**Comment by ktonon** [comment]
I see, for each project. np...

**Pull request merged**
